services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./audio:/app/audio

  dev:
    extends: app
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
