services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./audio:/app/audio

  dev:
    extends: app
    build:
      target: dev
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./index.html:/app/index.html
